USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=XXX-cdef
PACKAGE_VERSION=1.0
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.github.tobiasjwm
PAYLOAD=\
	pack-usr-local-outset-login-once-xxx-cdef.sh